# Generated by Django 5.0.2 on 2024-04-12 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_taken', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Criticality',
            fields=[
                ('criticality_id', models.AutoField(primary_key=True, serialize=False)),
                ('criticality_level', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_email', models.CharField(max_length=255)),
                ('passwords', models.CharField(max_length=255)),
                ('emp_fname', models.CharField(max_length=255)),
                ('emp_mname', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_lname', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.designations')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('is_private', models.BooleanField()),
                ('upload_date_time', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField()),
                ('document_name', models.CharField(max_length=255)),
                ('criticality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.criticality')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sender_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('records_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.actions')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.documents')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employees')),
            ],
        ),
    ]
