# Generated by Django 5.0.2 on 2024-04-15 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_documents_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.documents'),
            preserve_default=False,
        ),
    ]
