# Generated by Django 5.0.2 on 2024-04-23 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_departments_remove_employees_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='department',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='base.departments'),
            preserve_default=False,
        ),
    ]
