# Generated by Django 5.0.2 on 2024-04-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_documents_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='loc_id',
            field=models.TextField(default='1'),
        ),
    ]
