# Generated by Django 5.0.2 on 2024-04-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_documents_loc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='staff_status',
        ),
    ]
