# Generated by Django 5.0.2 on 2024-04-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_employees_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='designation',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='base.designations'),
            preserve_default=False,
        ),
    ]
